version: '2'
services:
    jhipsterapplicationgateway-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jhipsterApplicationGateway/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterApplicationGateway
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
